name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_go-create-version-branch.yml@61e6314e4ea0cf692c383e2d31cc94e4996e5331
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      dependencies: |
        [
          {"name": "Root Module",   "directory": "."},
          {"name": "golangci-lint", "directory": ".github/ci/lint"}
        ]
