name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump (auto, patch, feature, yearly, or rc)'
        required: true
        type: choice
        default: auto
        options:
          - auto
          - patch
          - feature
          - yearly
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  release:
    uses: valkyrjaio/.github/.github/workflows/_go-create-release.yml@6241ffe0c94f3e445c8c9ca9e631f7809da7ef3a
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      bump: ${{ inputs.bump }}
      info-file-path: template/constant/info.go
      info-file-name: Info
      dependencies: |
        [
          {"name": "Root Module",   "directory": "."},
          {"name": "golangci-lint", "directory": ".github/ci/lint"}
        ]
